###########
# Malmo Project
title:    'Food Hunting Go!'
subtitle: 'aaa Malmo Project of Machine Learning '


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
