###########
# Malmo Project
title:    'CS 175 Midori Hat Searching System'
subtitle: 'Machine Learning Malmo Project'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
